CREATE TABLE italy_provinces (
    id INT AUTO_INCREMENT PRIMARY KEY,
    province_name VARCHAR(100) NOT NULL,
    abbreviation CHAR(2) NOT NULL,
    cap_prefix CHAR(2) NOT NULL,
    region_name VARCHAR(100)
);

INSERT INTO italy_provinces (province_name, abbreviation, cap_prefix, region_name) VALUES
('Agrigento', 'AG', '92', 'Sicilia'),
('Alessandria', 'AL', '15', 'Piemonte'),
('Ancona', 'AN', '60', 'Marche'),
('Aosta', 'AO', '11', 'Valle d''Aosta'),
('Arezzo', 'AR', '52', 'Toscana'),
('Ascoli Piceno', 'AP', '63', 'Marche'),
('Asti', 'AT', '14', 'Piemonte'),
('Avellino', 'AV', '83', 'Campania'),
('Bari', 'BA', '70', 'Puglia'),
('Barletta-Andria-Trani', 'BT', '76', 'Puglia'),
('Belluno', 'BL', '32', 'Veneto'),
('Benevento', 'BN', '82', 'Campania'),
('Bergamo', 'BG', '24', 'Lombardia'),
('Biella', 'BI', '13', 'Piemonte'),
('Bologna', 'BO', '40', 'Emilia-Romagna'),
('Bolzano', 'BZ', '39', 'Trentino-Alto Adige'),
('Brescia', 'BS', '25', 'Lombardia'),
('Brindisi', 'BR', '72', 'Puglia'),
('Cagliari', 'CA', '09', 'Sardegna'),
('Caltanissetta', 'CL', '93', 'Sicilia'),
('Campobasso', 'CB', '86', 'Molise'),
('Caserta', 'CE', '81', 'Campania'),
('Catania', 'CT', '95', 'Sicilia'),
('Catanzaro', 'CZ', '88', 'Calabria'),
('Chieti', 'CH', '66', 'Abruzzo'),
('Como', 'CO', '22', 'Lombardia'),
('Cosenza', 'CS', '87', 'Calabria'),
('Cremona', 'CR', '26', 'Lombardia'),
('Crotone', 'KR', '88', 'Calabria'),
('Cuneo', 'CN', '12', 'Piemonte'),
('Enna', 'EN', '94', 'Sicilia'),
('Fermo', 'FM', '63', 'Marche'),
('Ferrara', 'FE', '44', 'Emilia-Romagna'),
('Firenze', 'FI', '50', 'Toscana'),
('Foggia', 'FG', '71', 'Puglia'),
('Forlì-Cesena', 'FC', '47', 'Emilia-Romagna'),
('Frosinone', 'FR', '03', 'Lazio'),
('Genova', 'GE', '16', 'Liguria'),
('Gorizia', 'GO', '34', 'Friuli-Venezia Giulia'),
('Grosseto', 'GR', '58', 'Toscana'),
('Imperia', 'IM', '18', 'Liguria'),
('Isernia', 'IS', '86', 'Molise'),
('L''Aquila', 'AQ', '67', 'Abruzzo'),
('La Spezia', 'SP', '19', 'Liguria'),
('Latina', 'LT', '04', 'Lazio'),
('Lecce', 'LE', '73', 'Puglia'),
('Lecco', 'LC', '23', 'Lombardia'),
('Livorno', 'LI', '57', 'Toscana'),
('Lodi', 'LO', '26', 'Lombardia'),
('Lucca', 'LU', '55', 'Toscana'),
('Macerata', 'MC', '62', 'Marche'),
('Mantova', 'MN', '46', 'Lombardia'),
('Massa-Carrara', 'MS', '54', 'Toscana'),
('Matera', 'MT', '75', 'Basilicata'),
('Messina', 'ME', '98', 'Sicilia'),
('Milano', 'MI', '20', 'Lombardia'),
('Modena', 'MO', '41', 'Emilia-Romagna'),
('Monza e della Brianza', 'MB', '20', 'Lombardia'),
('Napoli', 'NA', '80', 'Campania'),
('Novara', 'NO', '28', 'Piemonte'),
('Nuoro', 'NU', '08', 'Sardegna'),
('Oristano', 'OR', '09', 'Sardegna'),
('Padova', 'PD', '35', 'Veneto'),
('Palermo', 'PA', '90', 'Sicilia'),
('Parma', 'PR', '43', 'Emilia-Romagna'),
('Pavia', 'PV', '27', 'Lombardia'),
('Perugia', 'PG', '06', 'Umbria'),
('Pesaro e Urbino', 'PU', '61', 'Marche'),
('Pescara', 'PE', '65', 'Abruzzo'),
('Piacenza', 'PC', '29', 'Emilia-Romagna'),
('Pisa', 'PI', '56', 'Toscana'),
('Pistoia', 'PT', '51', 'Toscana'),
('Pordenone', 'PN', '33', 'Friuli-Venezia Giulia'),
('Potenza', 'PZ', '85', 'Basilicata'),
('Prato', 'PO', '59', 'Toscana'),
('Ragusa', 'RG', '97', 'Sicilia'),
('Ravenna', 'RA', '48', 'Emilia-Romagna'),
('Reggio Calabria', 'RC', '89', 'Calabria'),
('Reggio Emilia', 'RE', '42', 'Emilia-Romagna'),
('Rieti', 'RI', '02', 'Lazio'),
('Rimini', 'RN', '47', 'Emilia-Romagna'),
('Roma', 'RM', '00', 'Lazio'),
('Rovigo', 'RO', '45', 'Veneto'),
('Salerno', 'SA', '84', 'Campania'),
('Sassari', 'SS', '07', 'Sardegna'),
('Savona', 'SV', '17', 'Liguria'),
('Siena', 'SI', '53', 'Toscana'),
('Siracusa', 'SR', '96', 'Sicilia'),
('Sondrio', 'SO', '23', 'Lombardia'),
('Sud Sardegna', 'SU', '09', 'Sardegna'),
('Taranto', 'TA', '74', 'Puglia'),
('Teramo', 'TE', '64', 'Abruzzo'),
('Terni', 'TR', '05', 'Umbria'),
('Torino', 'TO', '10', 'Piemonte'),
('Trapani', 'TP', '91', 'Sicilia'),
('Trento', 'TN', '38', 'Trentino-Alto Adige'),
('Treviso', 'TV', '31', 'Veneto'),
('Trieste', 'TS', '34', 'Friuli-Venezia Giulia'),
('Udine', 'UD', '33', 'Friuli-Venezia Giulia'),
('Varese', 'VA', '21', 'Lombardia'),
('Venezia', 'VE', '30', 'Veneto'),
('Verbano-Cusio-Ossola', 'VB', '28', 'Piemonte'),
('Vercelli', 'VC', '13', 'Piemonte'),
('Verona', 'VR', '37', 'Veneto'),
('Vibo Valentia', 'VV', '89', 'Calabria'),
('Vicenza', 'VI', '36', 'Veneto'),
('Viterbo', 'VT', '01', 'Lazio');
